static const char *savestatusflags[]={
"1 TFFD3_PURE_WATER instance 1 volume of fluid [L] Param_Id=555 Data_Path=volume@elementaryhydraulicprops",
"1 TFFD3_PURE_WATER instance 1 mass of fluid [kg] Param_Id=556 Data_Path=mass@elementaryhydraulicprops",
"1 TFVF000 instance 1 duplicate of mass flow rate at port 1 [kg/s] Param_Id=1166 Data_Path=dm3@flowratesensor",
"1 TFVF000 instance 1 duplicate of enthalpy flow rate at port 1 [W] Param_Id=1167 Data_Path=dmh3@flowratesensor",
"1 TFVF000 instance 1 duplicate of volume at port 1 [cm**3] Param_Id=1168 Data_Path=vol3@flowratesensor",
"1 TFVF000 instance 1 duplicate of derivative of volume at port 1 [L/min] Param_Id=1169 Data_Path=dvol3@flowratesensor",
"1 TFVF000 instance 1 duplicate of flow index at port 1 [tfflow] Param_Id=1170 Data_Path=flowid3@flowratesensor",
"1 TFTK0 instance 1 tank pressure [barA] Param_Id=872 Data_Path=p1@tank01_2",
"1 TFTK0 instance 1 tank temperature [degC] Param_Id=873 Data_Path=t1@tank01_2",
"1 HIDDEN Param_Id=874",
"0 HIDDEN Param_Id=869",
"1 TFPUC0_SENSED instance 1 mass flow rate at port 1 [kg/s] Param_Id=956 Data_Path=dm1@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 enthalpy flow rate at port 1 [W] Param_Id=957 Data_Path=dmh1@tf_centrif_pump_1",
"1 HIDDEN Param_Id=958",
"1 HIDDEN Param_Id=959",
"1 HIDDEN Param_Id=960",
"1 TFTK0 instance 2 tank pressure [barA] Param_Id=889 Data_Path=p1@tank01_3",
"1 TFTK0 instance 2 tank temperature [degC] Param_Id=890 Data_Path=t1@tank01_3",
"1 HIDDEN Param_Id=891",
"0 HIDDEN Param_Id=886",
"1 UD00 instance 1 user defined duty cycle output Param_Id=1008 Data_Path=output@piecewiselinear_2",
"1 CTRPID0 instance 1 pid output at port 2 Param_Id=1315 Data_Path=v@pidtune",
"1 TFVF000 instance 1 duplicate of pressure at port 3 [barA] Param_Id=1157 Data_Path=p1@flowratesensor",
"1 TFVF000 instance 1 duplicate of temperature at port 3 [degC] Param_Id=1158 Data_Path=t1@flowratesensor",
"1 TFVF000 instance 1 duplicate of node index at port 3 [tfnode] Param_Id=1159 Data_Path=nodeid1@flowratesensor",
"1 TFVORF0 instance 1 mass flow rate at port 2 [kg/s] Param_Id=1053 Data_Path=dm2@variableorifice_1",
"1 TFVORF0 instance 1 enthalpy flow rate at port 2 [W] Param_Id=1054 Data_Path=dmh2@variableorifice_1",
"1 HIDDEN Param_Id=1055",
"1 HIDDEN Param_Id=1056",
"1 HIDDEN Param_Id=1057",
"1 TFPUC0_SENSED instance 1 pressure at port 2 [barA] Param_Id=964 Data_Path=p2@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 temperature at port 2 [degC] Param_Id=965 Data_Path=t2@tf_centrif_pump_1",
"1 HIDDEN Param_Id=966",
"1 TFVORF0 instance 1 sign reversed duplicate of mass flow rate at port 2 [kg/s] Param_Id=1061 Data_Path=dm3@variableorifice_1",
"1 TFVORF0 instance 1 sign reversed duplicate of enthalpy flow rate at port 2 [W] Param_Id=1062 Data_Path=dmh3@variableorifice_1",
"1 HIDDEN Param_Id=1063",
"1 HIDDEN Param_Id=1064",
"1 HIDDEN Param_Id=1065",
"1 TFVORF0 instance 1 flow coefficient (Cq) Param_Id=1036 Data_Path=cq@variableorifice_1",
"1 TFVORF0 instance 1 singular pressure drop coefficient (zeta) Param_Id=1037 Data_Path=zeta@variableorifice_1",
"1 TFVORF0 instance 1 flow coefficient (Cv) Param_Id=1038 Data_Path=cv@variableorifice_1",
"1 TFVORF0 instance 1 flow coefficient (Kv) Param_Id=1039 Data_Path=kv@variableorifice_1",
"1 TFVORF0 instance 1 flow number (lambda) Param_Id=1040 Data_Path=lambda@variableorifice_1",
"1 TFVORF0 instance 1 Reynolds number Param_Id=1041 Data_Path=re@variableorifice_1",
"1 TFVORF0 instance 1 mean fluid velocity [m/s] Param_Id=1042 Data_Path=flv@variableorifice_1",
"1 TFVORF0 instance 1 cross-sectional area [mm**2] Param_Id=1043 Data_Path=marea@variableorifice_1",
"1 TFVORF0 instance 1 hydraulic diameter [mm] Param_Id=1044 Data_Path=mhdiam@variableorifice_1",
"1 TFVORF0 instance 1 pressure drop (p3 - p2) [bar] Param_Id=1045 Data_Path=deltap@variableorifice_1",
"1 TFVORF0 instance 1 jet temperature [degC] Param_Id=1046 Data_Path=tjet@variableorifice_1",
"1 TFVORF0 instance 1 volumetric flow rate at port 2 [L/min] Param_Id=1047 Data_Path=q2@variableorifice_1",
"0 HIDDEN Param_Id=1049",
"1 TFVF000 instance 1 output flow rate signal Param_Id=1165 Data_Path=outv@flowratesensor",
"1 TFVF000 instance 1 volumetric flow rate [L/min] Param_Id=1155 Data_Path=qv@flowratesensor",
"1 TFVF000 instance 1 fluid density [kg/m**3] Param_Id=1156 Data_Path=rho@flowratesensor",
"1 SIGRECEI0 instance 1 receiver output Param_Id=2815 Data_Path=output@dynamic_receiver_5",
"1 CTRPID0 instance 1 control error (= setpoint - actual) Param_Id=1298 Data_Path=u@pidtune",
"1 CTRPID0 instance 1 control error derivative [1/s] Param_Id=1299 Data_Path=du@pidtune",
"1 CTRPID0 instance 1 proportional part Param_Id=1300 Data_Path=ppart@pidtune",
"1 CTRPID0 instance 1 integral part Param_Id=1301 Data_Path=ipart@pidtune",
"1 CTRPID0 instance 1 derivative part Param_Id=1302 Data_Path=dpart@pidtune",
"1 CTRPID0 instance 1 internal state for derivative estimate Param_Id=1303 Data_Path=w@pidtune",
"1 CTRPID0 instance 1 anti windup method - Linked variable Param_Id=1304 Is_Linked_Variable=1 Data_Path=antiwind0GEN@pidtune",
"1 CTRPID0 instance 1 proportional gain - Linked variable Param_Id=1305 Is_Linked_Variable=1 Data_Path=Kp0GEN@pidtune",
"1 CTRPID0 instance 1 integral gain - Linked variable Param_Id=1306 Is_Linked_Variable=1 Data_Path=Ki0GEN@pidtune",
"1 CTRPID0 instance 1 derivative gain - Linked variable Param_Id=1307 Is_Linked_Variable=1 Data_Path=Kd0GEN@pidtune",
"1 CTRPID0 instance 1 time constant for derivative estimate - Linked variable [s] Param_Id=1308 Is_Linked_Variable=1 Data_Path=tau0GEN@pidtune",
"1 CTRPID0 instance 1 minimum permitted output value - Linked variable Param_Id=1309 Is_Linked_Variable=1 Data_Path=outmin0GEN@pidtune",
"1 CTRPID0 instance 1 maximum permitted output value - Linked variable Param_Id=1310 Is_Linked_Variable=1 Data_Path=outmax0GEN@pidtune",
"1 CTRPID0 instance 1 backtracking gain - Linked variable Param_Id=1311 Is_Linked_Variable=1 Data_Path=Ks0GEN@pidtune",
"1 CTRPID0 instance 1 hysteresis - Linked variable Param_Id=1312 Is_Linked_Variable=1 Data_Path=hyst0GEN@pidtune",
"1 CTRPID0 instance 1 limit output - Linked variable Param_Id=1313 Is_Linked_Variable=1 Data_Path=outlim0GEN@pidtune",
"1 CONS00 instance 1 output Param_Id=1799 Data_Path=out@constant",
"1 CONS00 instance 1 constant value - Linked variable Param_Id=1798 Is_Linked_Variable=1 Data_Path=k0GEN@constant",
"1 SIGTRANS0 instance 4 transmitter output Param_Id=2963 Data_Path=transout@dynamic_transmitter_5",
"1 SIGRECEI0 instance 2 receiver output Param_Id=2820 Data_Path=output@dynamic_receiver_6",
"1 SIGTRANS0 instance 5 transmitter output Param_Id=2968 Data_Path=transout@dynamic_transmitter_6",
"1 TFPUC0_SENSED instance 1 shaft torque [Nm] Param_Id=972 Data_Path=TShaft@tf_centrif_pump_1",
"1 PMV00 instance 1 rotary speed output [rev/min] Param_Id=2823 Data_Path=omega@pmover01v_1",
"1 SIGTRANS0 instance 1 transmitter output Param_Id=2827 Data_Path=transout@dynamic_transmitter_7",
"1 INTVARSENSOR0 instance 1 volumetric flow rate Param_Id=3032 Data_Path=output@tf_centrif_pump_1.intvarsensor",
"1 SIGTRANS0 instance 2 transmitter output Param_Id=2832 Data_Path=transout@dynamic_transmitter_8",
"1 INTVARSENSOR0 instance 2 pressure increase Param_Id=3035 Data_Path=output@tf_centrif_pump_1.intvarsensor_1",
"1 SIGTRANS0 instance 3 transmitter output Param_Id=2837 Data_Path=transout@dynamic_transmitter_9",
"1 INTVARSENSOR0 instance 3 mechanical power Param_Id=3038 Data_Path=output@tf_centrif_pump_1.intvarsensor_2",
"1 AMESIM_INTERFACE instance 1 flowrate_target Param_Id=2987 Data_Path=flowrate_target@amesim_interface",
"1 AMESIM_INTERFACE instance 1 pump_speed Param_Id=2986 Data_Path=pump_speed@amesim_interface",
"1 SIGRECEI0 instance 3 receiver output Param_Id=2973 Data_Path=output@dynamic_receiver_7",
"1 SIGRECEI0 instance 4 receiver output Param_Id=2978 Data_Path=output@dynamic_receiver_8",
"1 SIGRECEI0 instance 5 receiver output Param_Id=2983 Data_Path=output@dynamic_receiver_9",
"1 TFPUC0_SENSED instance 1 volumetric flow rate [L/min] Param_Id=939 Data_Path=q2@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 reference density [kg/m**3] Param_Id=940 Data_Path=rhoref@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 pressure increase [bar] Param_Id=941 Data_Path=dP@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 mechanical power [W] Param_Id=942 Data_Path=pmech@tf_centrif_pump_1",
"1 TFPUC0_SENSED instance 1 global efficiency Param_Id=943 Data_Path=feff@tf_centrif_pump_1",
"0 HIDDEN Param_Id=950",
"0 HIDDEN Param_Id=953"
};
static const int savestatusflags_length = 96;
